image:
  name: golang:1.16.3-alpine

stages:
  - build
  - push

build:
  stage: build
  script:
    - mkdir bin
    - go test -i -c -vet=off -o=bin/prometheus_alerts_tests.test test/prometheus_alerts_test.go
  artifacts:
    paths:
      - bin/
  only:
    - branches

build_push:
  stage: push
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - cp $DOCKER_AUTH_CONFIG /kaniko/.docker/config.json
    - cp $CI_REGISTRY_CA /kaniko/ssl/certs/additional-ca-cert-bundle.crt
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --skip-tls-verify
      --destination $CI_REGISTRY_IMAGE:latest
      --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
      --registry-certificate ${CI_REGISTRY}:443=$CI_REGISTRY_CA
      --cache=true
  dependencies:
    - build
  only:
    - main